app:
  name: Multi-module Demo
  description: Seed multi-module project
  version: 1
  security:
    enabled: ${SECURITY_ENABLE:false}
    realm: ${KEYCLOAK_REALM_NAME:master}
    clientId: ${KEYCLOAK_CLIENT_ID:swd_public_client}
    roleClientId: ${KEYCLOAK_ROLE_CLIENT_ID:swd_public_client}
    auth-server-url: ${KEYCLOAK_AUTH_URL:https://auth.dev.smart-x.smartsenselabs.com}
    auth-url: ${app.security.auth-server-url}/realms/${app.security.realm}/protocol/openid-connect/auth
    token-url: ${app.security.auth-server-url}/realms/${app.security.realm}/protocol/openid-connect/token
    refresh-token-url: ${KEYCLOAK_TOKEN_URL}
    corsOrigins: "*"

server:
  port: ${APP_PORT:8080}
  shutdown: graceful
  servlet:
    contextPath: /api/app
  compression:
    enabled: true
    min-response-size: 1024
#Add message path for i18n support

springdoc:
  swagger-ui:
    oauth:
      clientId: ${KEYCLOAK_CLIENT_ID:swd_public_client}
    disable-swagger-default-url: true
    path: /ui/swagger-ui
    show-common-extensions: true
    csrf:
      enabled: true
  api-docs:
    path: /docs/api-docs

management:
  health:
    db:
      enabled: true
    diskspace:
      enabled: false
    livenessstate:
      enabled: true
    ping:
      enabled: false
    readinessstate:
      enabled: true
    probes:
      enabled: true
  endpoint:
    health:
      showDetails: ALWAYS

logging:
  level:
    root: INFO
    org.cofinity.sw: DEBUG
    com.smartsensesolutions: DEBUG

messages:
  bundle:
    path: classpath:i18n/messages

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:multi-module-demo}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          #Issuer-uri indicates the iss claims from jwt token
          issuer-uri: ${app.security.auth-server-url}/realms/${app.security.realm}
          jwk-set-uri: ${app.security.auth-server-url}/realms/${app.security.realm}/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:50MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:51MB}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

feign:
  default:
    connectionTimeoutMillis: ${RETRY_CONNECTION_TIMEOUT_MILLI:200}
    readTimeoutMillis: ${RETRY_READ_TIMEOUT_MILLI:500}
    maxIdleConnections: ${RETRY_MAX_IDLE_CONNECTION:10}
    keepAliveDurationMinutes: ${RETRY_ALIVE_DURATION_MIN:5}
    maxRetryAttempt: ${RETRY_MAX_ATTEMPT:5}
    retryInterval: ${RETRY_INTERVAL_MILLI:2000}
